const en_to_fr = {
  Afghanistan: "Afghanistan",
  Albania: "Albanie",
  Algeria: "Algérie",
  Andorra: "Andorre",
  Angola: "Angola",
  AntiguaandBarbuda: "Antigua-et-Barbuda",
  Argentina: "Argentine",
  Armenia: "Arménie",
  Australia: "Australie",
  Austria: "Autriche",
  Azerbaijan: "Azerbaïdjan",
  Bahamas: "Bahamas",
  Bahrain: "Bahreïn",
  Bangladesh: "Bangladesh",
  Barbados: "Barbade",
  Belarus: "Biélorussie",
  Belgium: "Belgique",
  Belize: "Belize",
  Benin: "Bénin",
  Bhutan: "Bhoutan",
  Bolivia: "Bolivie",
  BosniaandHerzegovina: "Bosnie-Herzégovine",
  Botswana: "Botswana",
  Brazil: "Brésil",
  Brunei: "Brunéi",
  Bulgaria: "Bulgarie",
  BurkinaFaso: "Burkina Faso",
  Burundi: "Burundi",
  CaboVerde: "Cap-Vert",
  Cambodia: "Cambodge",
  Cameroon: "Cameroun",
  Canada: "Canada",
  CentralAfricanRepublic: "République centrafricaine",
  Chad: "Tchad",
  Chile: "Chili",
  China: "Chine",
  Colombia: "Colombie",
  Comoros: "Comores",
  Congo: "Congo",
  CostaRica: "Costa Rica",
  Croatia: "Croatie",
  Cuba: "Cuba",
  Cyprus: "Chypre",
  CzechRepublic: "République tchèque",
  Denmark: "Danemark",
  Djibouti: "Djibouti",
  Dominica: "Dominique",
  DominicanRepublic: "République dominicaine",
  Ecuador: "Équateur",
  Egypt: "Égypte",
  ElSalvador: "Salvador",
  EquatorialGuinea: "Guinée équatoriale",
  Eritrea: "Érythrée",
  Estonia: "Estonie",
  Eswatini: "Eswatini",
  Ethiopia: "Éthiopie",
  Fiji: "Fidji",
  Finland: "Finlande",
  France: "France",
  Gabon: "Gabon",
  Gambia: "Gambie",
  Georgia: "Géorgie",
  Germany: "Allemagne",
  Ghana: "Ghana",
  Greece: "Grèce",
  Grenada: "Grenade",
  Guatemala: "Guatemala",
  Guinea: "Guinée",
  GuineaBissau: "Guinée-Bissau",
  Guyana: "Guyana",
  Haiti: "Haïti",
  Honduras: "Honduras",
  Hungary: "Hongrie",
  Iceland: "Islande",
  India: "Inde",
  Indonesia: "Indonésie",
  Iran: "Iran",
  Iraq: "Irak",
  Ireland: "Irlande",
  Israel: "Israël",
  Italy: "Italie",
  Jamaica: "Jamaïque",
  Japan: "Japon",
  Jordan: "Jordanie",
  Kazakhstan: "Kazakhstan",
  Kenya: "Kenya",
  Kiribati: "Kiribati",
  Kuwait: "Koweït",
  Kyrgyzstan: "Kirghizistan",
  Laos: "Laos",
  Latvia: "Lettonie",
  Lebanon: "Liban",
  Lesotho: "Lesotho",
  Liberia: "Libéria",
  Libya: "Libye",
  Liechtenstein: "Liechtenstein",
  Lithuania: "Lituanie",
  Luxembourg: "Luxembourg",
  Madagascar: "Madagascar",
  Malawi: "Malawi",
  Malaysia: "Malaisie",
  Maldives: "Maldives",
  Mali: "Mali",
  Malta: "Malte",
  MarshallIslands: "Îles Marshall",
  Mauritania: "Mauritanie",
  Mauritius: "Maurice",
  Mexico: "Mexique",
  Micronesia: "Micronésie",
  Moldova: "Moldavie",
  Monaco: "Monaco",
  Mongolia: "Mongolie",
  Montenegro: "Monténégro",  
  Montserrat: "Montserrat",
  Morocco: "Maroc",
  Mozambique: "Mozambique",
  Myanmar: "Myanmar",
  Namibia: "Namibie",
  Nauru: "Nauru",
  Nepal: "Népal",
  Netherlands: "Pays-Bas",
  NewCaledonia: "Nouvelle-Calédonie",
  NewZealand: "Nouvelle-Zélande",
  Nicaragua: "Nicaragua",
  Niger: "Niger",
  Nigeria: "Nigéria",
  Niue: "Niue",
  NorthKorea: "Corée du Nord",
  NorthMacedonia: "Macédoine du Nord",
  NorthernMarianaIslands: "Îles Mariannes du Nord",
  Norway: "Norvège",
  Oman: "Oman",
  Pakistan: "Pakistan",
  Palau: "Palaos",
  Palestine: "Palestine",
  Panama: "Panama",
  PapuaNewGuinea: "Papouasie-Nouvelle-Guinée",
  Paraguay: "Paraguay",
  Peru: "Pérou",
  Philippines: "Philippines",
  PitcairnIslands: "Îles Pitcairn",
  Poland: "Pologne",
  Portugal: "Portugal",
  PuertoRico: "Porto Rico",
  Qatar: "Qatar",
  Romania: "Roumanie",
  Russia: "Russie",
  Rwanda: "Rwanda",
  SaintBarthelemy: "Saint-Barthélemy",
  SaintHelena: "Sainte-Hélène",
  SaintKittsandNevis: "Saint-Kitts-et-Nevis",
  SaintLucia: "Sainte-Lucie",
  SaintMartin: "Saint-Martin",
  SaintPierreandMiquelon: "Saint-Pierre-et-Miquelon",
  SaintVincentandtheGrenadines: "Saint-Vincent-et-les-Grenadines",
  Samoa: "Samoa",
  SanMarino: "Saint-Marin",
  SaoTomeandPrincipe: "Sao Tomé-et-Príncipe",
  SaudiArabia: "Arabie saoudite",
  Senegal: "Sénégal",
  Serbia: "Serbie",
  Seychelles: "Seychelles",
  SierraLeone: "Sierra Leone",
  Singapore: "Singapour",
  SintMaarten: "Sint Maarten",
  Slovakia: "Slovaquie",
  Slovenia: "Slovénie",
  SolomonIslands: "Îles Salomon",
  Somalia: "Somalie",
  SouthAfrica: "Afrique du Sud",
  SouthGeorgiaandtheSouthSandwichIslands: "Géorgie du Sud-et-les Îles Sandwich du Sud",
  SouthKorea: "Corée du Sud",
  SouthSudan: "Soudan du Sud",
  Spain: "Espagne",
  SriLanka: "Sri Lanka",
  Sudan: "Soudan",
  Suriname: "Suriname",
  SvalbardandJanMayen: "Svalbard et Jan Mayen",
  Sweden: "Suède",
  Switzerland: "Suisse",
  Syria: "Syrie",
  Taiwan: "Taïwan",
  Tajikistan: "Tadjikistan",
  Tanzania: "Tanzanie",
  Thailand: "Thaïlande",
  TimorLeste: "Timor oriental",
  Togo: "Togo",
  Tokelau: "Tokelau",
  Tonga: "Tonga",
  TrinidadandTobago: "Trinité-et-Tobago",
  Tunisia: "Tunisie",
  Turkey: "Turquie",
  Turkmenistan: "Turkménistan",
  TurksandCaicosIslands: "Îles Turques-et-Caïques",
  Tuvalu: "Tuvalu",
  Uganda: "Ouganda",
  Ukraine: "Ukraine",
  UnitedArabEmirates: "Émirats arabes unis",
  UnitedKingdom: "Royaume-Uni",
  UnitedStates: "États-Unis",
  Uruguay: "Uruguay",
  Uzbekistan: "Ouzbékistan",
  Vanuatu: "Vanuatu",
  VaticanCity: "Cité du Vatican",
  Venezuela: "Venezuela",
  Vietnam: "Vietnam",
  VirginIslandsUS: "Îles Vierges des États-Unis",
  WallisandFutuna: "Wallis-et-Futuna",
  WesternSahara: "Sahara occidental",
  Yemen: "Yémen",
  Zambia: "Zambie",
  Zimbabwe: "Zimbabwe"
};


const countryNames = {
  "Åland Islands": "Quần đảo Åland",
  Albania: "Albania",
  Algeria: "Algeria",
  "American Samoa": "Samoa thuộc Mỹ",
  Andorra: "Andorra",
  Angola: "Angola",
  Anguilla: "Anguilla",
  Antarctica: "Châu Nam Cực",
  "Antigua and Barbuda": "Antigua và Barbuda",
  Argentina: "Argentina",
  Armenia: "Armenia",
  Aruba: "Aruba",
  Australia: "Úc",
  Austria: "Áo",
  Azerbaijan: "Azerbaijan",
  Bahamas: "Bahamas",
  Bahrain: "Bahrain",
  Bangladesh: "Bangladesh",
  Barbados: "Barbados",
  Belarus: "Belarus",
  Belgium: "Bỉ",
  Belize: "Belize",
  Benin: "Bénin",
  Bermuda: "Bermuda",
  Bhutan: "Bhutan",
  Bolivia: "Bolivia",
  "Bonaire, Sint Eustatius and Saba": "Bonaire, Sint Eustatius và Saba",
  Bosnia: "Bosnia",
  Botswana: "Botswana",
  "Bouvet Island": "Đảo Bouvet",
  Brazil: "Brazil",
  "British Indian Ocean Territory": "Lãnh thổ Ấn Độ Dương thuộc Anh",
  "British Virgin Islands": "Quần đảo Virgin thuộc Anh",
  Brunei: "Brunei",
  Bulgaria: "Bulgaria",
  "Burkina Faso": "Burkina Faso",
  Burundi: "Burundi",
  Cambodia: "Campuchia",
  Cameroon: "Cameroon",
  Canada: "Canada",
  "Cape Verde": "Cabo Verde",
  "Cayman Islands": "Quần đảo Cayman",
  "Central African Republic": "Cộng hòa Trung Phi",
  Chad: "Chad",
  Chile: "Chile",
  China: "Trung Quốc",
  "Christmas Island": "Đảo Giáng Sinh",
  "Cocos (Keeling) Islands": "Quần đảo Cocos (Keeling)",
  Colombia: "Colombia",
  Comoros: "Comoros",
  Congo: "Congo",
  "Cook Islands": "Quần đảo Cook",
  "Costa Rica": "Costa Rica",
  Croatia: "Croatia",
  Cuba: "Cuba",
  Curaçao: "Curaçao",
  Cyprus: "Síp",
  "Czech Republic": "Cộng hòa Séc",
  Denmark: "Đan Mạch",
  Djibouti: "Djibouti",
  Dominica: "Dominica",
  "Dominican Republic": "Cộng hòa Dominica",
  Ecuador: "Ecuador",
  Egypt: "Ai Cập",
  "El Salvador": "El Salvador",
  "Equatorial Guinea": "Guinea Xích Đạo",
  Eritrea: "Eritrea",
  Estonia: "Estonia",
  Eswatini: "Eswatini",
  Ethiopia: "Ethiopia",
  "Falkland Islands": "Quần đảo Falkland",
  "Faroe Islands": "Quần đảo Faroe",
  Fiji: "Fiji",
  Finland: "Phần Lan",
  France: "Pháp",
  "French Guiana": "Guiana thuộc Pháp",
  "French Polynesia": "Polynesia thuộc Pháp",
  "French Southern Territories": "Lãnh thổ miền Nam thuộc Pháp",
  Gabon: "Gabon",
  Gambia: "Gambia",
  Georgia: "Georgia",
  Germany: "Đức",
  Ghana: "Ghana",
  Gibraltar: "Gibraltar",
  Greece: "Hy Lạp",
  Greenland: "Greenland",
  Grenada: "Grenada",
  Guadeloupe: "Guadeloupe",
  Guam: "Guam",
  Guatemala: "Guatemala",
  Guernsey: "Guernsey",
  Guinea: "Guinea",
  "Guinea-Bissau": "Guinea-Bissau",
  Guyana: "Guyana",
  Haiti: "Haiti",
  "Heard Island and McDonald Islands": "Đảo Heard và Quần đảo McDonald",
  Honduras: "Honduras",
  "Hong Kong": "Hồng Kông",
  Hungary: "Hungary",
  Iceland: "Iceland",
  India: "Ấn Độ",
  Indonesia: "Indonesia",
  Iran: "Iran",
  Iraq: "Iraq",
  Ireland: "Ireland",
  "Isle of Man": "Đảo Man",
  Israel: "Israel",
  Italy: "Ý",
  Jamaica: "Jamaica",
  Japan: "Nhật Bản",
  Jersey: "Jersey",
  Jordan: "Jordan",
  Kazakhstan: "Kazakhstan",
  Kenya: "Kenya",
  Kiribati: "Kiribati",
  Kosovo: "Kosovo",
  Kuwait: "Kuwait",
  Kyrgyzstan: "Kyrgyzstan",
  Laos: "Lào",
  Latvia: "Latvia",
  Lebanon: "Lebanon",
  Lesotho: "Lesotho",
  Liberia: "Liberia",
  Libya: "Libya",
  Liechtenstein: "Liechtenstein",
  Lithuania: "Lithuania",
  Luxembourg: "Luxembourg",
  Macao: "Macao",
  Madagascar: "Madagascar",
  Malawi: "Malawi",
  Malaysia: "Malaysia",
  Maldives: "Maldives",
  Mali: "Mali",
  Malta: "Malta",
  "Marshall Islands": "Quần đảo Marshall",
  Martinique: "Martinique",
  Mauritania: "Mauritania",
  Mauritius: "Mauritius",
  Mayotte: "Mayotte",
  Mexico: "Mexico",
  "Micronesia (Federated States of)": "Micronesia (Các Tiểu bang Liên hiệp)",
  Moldova: "Moldova",
  Monaco: "Monaco",
  Mongolia: "Mông Cổ",
  Montenegro: "Montenegro",
  Montserrat: "Montserrat",
  Morocco: "Maroc",
  Mozambique: "Mozambique",
  Myanmar: "Myanmar",
  Namibia: "Namibia",
  Nauru: "Nauru",
  Nepal: "Nepal",
  Netherlands: "Hà Lan",
  "New Caledonia": "New Caledonia",
  "New Zealand": "New Zealand",
  Nicaragua: "Nicaragua",
  Niger: "Niger",
  Nigeria: "Nigeria",
  Niue: "Niue",
  "Norfolk Island": "Đảo Norfolk",
  "North Korea": "Bắc Triều Tiên",
  "North Macedonia": "Bắc Macedonia",
  "Northern Mariana Islands": "Quần đảo Bắc Mariana",
  Norway: "Na Uy",
  Oman: "Oman",
  Pakistan: "Pakistan",
  Palau: "Palau",
  Palestine: "Palestine",
  Panama: "Panama",
  "Papua New Guinea": "Papua New Guinea",
  Paraguay: "Paraguay",
  Peru: "Peru",
  Philippines: "Philippines",
  Pitcairn: "Quần đảo Pitcairn",
  Poland: "Ba Lan",
  Portugal: "Bồ Đào Nha",
  "Puerto Rico": "Puerto Rico",
  Qatar: "Qatar",
  Réunion: "Réunion",
  Romania: "Romania",
  Russia: "Nga",
  Rwanda: "Rwanda",
  "Saint Barthélemy": "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha": "Saint Helena, Ascension và Tristan da Cunha",
  "Saint Kitts and Nevis": "Saint Kitts và Nevis",
  "Saint Lucia": "Saint Lucia",
  "Saint Martin (French part)": "Saint Martin (Phần thuộc Pháp)",
  "Saint Pierre and Miquelon": "Saint Pierre và Miquelon",
  "Saint Vincent and the Grenadines": "Saint Vincent và Grenadines",
  Samoa: "Samoa",
  "San Marino": "San Marino",
  "Sao Tome and Principe": "Sao Tome và Principe",
  "Saudi Arabia": "Ả Rập Xê Út",
  Senegal: "Senegal",
  Serbia: "Serbia",
  Seychelles: "Seychelles",
  "Sierra Leone": "Sierra Leone",
  Singapore: "Singapore",
  "Sint Maarten (Dutch part)": "Sint Maarten (Phần thuộc Hà Lan)",
  Slovakia: "Slovakia",
  Slovenia: "Slovenia",
  "Solomon Islands": "Quần đảo Solomon",
  Somalia: "Somalia",
  "South Africa": "Nam Phi",
  "South Georgia and the South Sandwich Islands": "Nam Georgia và Quần đảo South Sandwich",
  "South Korea": "Hàn Quốc",
  "South Sudan": "Nam Sudan",
  Spain: "Tây Ban Nha",
  "Sri Lanka": "Sri Lanka",
  Sudan: "Sudan",
  Suriname: "Suriname",
  "Svalbard and Jan Mayen": "Svalbard và Jan Mayen",
  Swaziland: "Swaziland",
  Sweden: "Thụy Điển",
  Switzerland: "Thụy Sĩ",
  Syria: "Syria",
  "Taiwan, Province of China": "Đài Loan, Trung Quốc",
  Tajikistan: "Tajikistan",
  Tanzania: "Tanzania",
  Thailand: "Thái Lan",
  "Timor-Leste": "Timor-Leste",
  Togo: "Togo",
  Tokelau: "Tokelau",
  Tonga: "Tonga",
  "Trinidad and Tobago": "Trinidad và Tobago",
  Tunisia: "Tunisia",
  Turkey: "Thổ Nhĩ Kỳ",
  Turkmenistan: "Turkmenistan",
  "Turks and Caicos Islands": "Quần đảo Turks và Caicos",
  Tuvalu: "Tuvalu",
  Uganda: "Uganda",
  Ukraine: "Ukraine",
  "United Arab Emirates": "Các Tiểu Vương quốc Ả Rập Thống nhất",
  "United Kingdom": "Vương quốc Anh",
  "United States": "Hoa Kỳ",
  "United States Minor Outlying Islands": "Các đảo nhỏ xa trung tâm của Hoa Kỳ",
  Uruguay: "Uruguay",
  Uzbekistan: "Uzbekistan",
  Vanuatu: "Vanuatu",
  "Vatican City": "Thành Vatican",
  Venezuela: "Venezuela",
  Vietnam: "Việt Nam",
  "Virgin Islands (British)": "Quần đảo Virgin (Anh)",
  "Virgin Islands (U.S.)": "Quần đảo Virgin (Hoa Kỳ)",
  "Wallis and Futuna": "Wallis và Futuna",
  "Western Sahara": "Tây Sahara",
  Yemen: "Yemen",
  Zambia: "Zambia",
  Zimbabwe: "Zimbabwe"
};